/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.60
 * Generated at: 2022-07-05 01:39:06 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.idol.model.ProductDTO;
import com.idol.model.InquiryDTO;
import java.util.List;
import com.idol.model.MemberDTO;
import com.idol.model.MemberDTO;

public final class mypage_005fqnaList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("/WEB-INF/views/member/../include/user_bottom.jsp", Long.valueOf(1656899132952L));
    _jspx_dependants.put("jar:file:/C:/NCS/workspace(spring)/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/IdolProject/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/views/member/../include/user_top.jsp", Long.valueOf(1656895166322L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1652771076240L));
    _jspx_dependants.put("jar:file:/C:/NCS/workspace(spring)/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/IdolProject/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.idol.model.InquiryDTO");
    _jspx_imports_classes.add("com.idol.model.MemberDTO");
    _jspx_imports_classes.add("com.idol.model.ProductDTO");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>마이페이지> 문의내역</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"http://code.jquery.com/jquery-3.6.0.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"./resources/js/member.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"./resources/css/member.css?v=2022063010\">\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write(" <!--로그인회원 정보 저장 -->\r\n");
      out.write("	");
      if (_jspx_meth_c_005fset_005f1(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      out.write('	');
      if (_jspx_meth_c_005fset_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("	<head>\r\n");
      out.write("		<meta charset=\"UTF-8\">\r\n");
      out.write("		<link rel=\"stylesheet\" href=\"./resources/css/all.min.css\">\r\n");
      out.write("		<link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("		<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("		<link href=\"https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@300;400;500;700&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("	    <link rel=\"stylesheet\" href=\"./resources/css/global.css\" />\r\n");
      out.write("	    <link rel=\"stylesheet\" href=\"./resources/css/gnb.css\" />\r\n");
      out.write("	    <link rel=\"stylesheet\" href=\"./resources/css/main.css\" />\r\n");
      out.write("		<title>YOUR CELEB</title>\r\n");
      out.write("		<script type=\"text/javascript\">\r\n");
      out.write("		function loginAlert() {\r\n");
      out.write("		      alert(\"사용 권한이 없습니다. 로그인 해주세요\");\r\n");
      out.write("		  } \r\n");
      out.write("		</script>\r\n");
      out.write("	</head>\r\n");
      out.write("	<body>\r\n");
      out.write("		<!-- include header -->\r\n");
      out.write("              <div id=\"g_nav\">\r\n");
      out.write("                 <ul class=\"main_login_section\">\r\n");
      out.write("				");
 if(session.getAttribute("login_id") == null){ 
				 
      out.write("\r\n");
      out.write("           			<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/login.do\">Login</a></li>\r\n");
      out.write("          			<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/join.do\">Join</a></li>\r\n");
      out.write("				");
} else{ 
      out.write("\r\n");
      out.write("                    <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/logout.do\">Logout</a></li>\r\n");
      out.write("                ");
} 
      out.write("	\r\n");
      out.write("                 </ul>\r\n");
      out.write("              </div>\r\n");
      out.write("   		<header id=\"header\">\r\n");
      out.write("      <div class=\"gnb\">\r\n");
      out.write("        <div class=\"gnb-wrap\">\r\n");
      out.write("	      <div class=\"logo\"><a href=\"");
      out.print(request.getContextPath());
      out.write("/\"><img src=\"././resources/upload/logo.png\"></a></div>\r\n");
      out.write("          <div class=\"gnb-menu\">\r\n");
      out.write("            <ul>\r\n");
      out.write("              <li>\r\n");
      out.write("                <a href=\"#\" class=\"active-link\" id=\"artist\">ARTIST</a>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li>\r\n");
      out.write("                <a href=\"");
      out.print(request.getContextPath());
      out.write("/product_list.do?cno=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${100}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" class=\"active-link\" id=\"product\">PRODUCT</a>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/community_boardList.do\">FORUM</a></li>\r\n");
      out.write("              <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/event_list.do?board_id=1&category_id=1\">EVENT</a></li>\r\n");
      out.write("              <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/whole_ranking.do\">MEMBERS</a></li>\r\n");
      out.write("              <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/used_list.do\">MARKET</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("            \r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("          <div class=\"gnb-tool\">\r\n");
      out.write("            <ul>\r\n");
      out.write("            <!-- 로그인이 안 되어 있을 경우 -->\r\n");
      out.write("            ");
 if(session.getAttribute("login_id")==null){ 
      out.write("\r\n");
      out.write("              <li>\r\n");
      out.write("              <!-- MYPAGE -->\r\n");
      out.write("                <a href=\"#\" onclick=\"loginAlert()\"><i class=\"fa-solid fa-user\"></i></a>\r\n");
      out.write("              </li>\r\n");
      out.write("              <!-- SEARCH -->\r\n");
      out.write("              <li><a href=\"#\"><i class=\"fa-solid fa-magnifying-glass\"></i></a></li>\r\n");
      out.write("				\r\n");
      out.write("			  <!-- CART -->\r\n");
      out.write("              <li><a href=\"#\" onclick=\"loginAlert()\"><i class=\"fa-solid fa-cart-shopping\"></i></a></li>\r\n");
      out.write("            \r\n");
      out.write("            </ul>\r\n");
      out.write("            ");
}else { 
      out.write("\r\n");
      out.write("            <ul>\r\n");
      out.write("              <li>\r\n");
      out.write("              <!-- MYPAGE -->\r\n");
      out.write("                <a href=\"");
      out.print(request.getContextPath());
      out.write("/myfeed.do?id=");
      out.print((String)session.getAttribute("login_id"));
      out.write("\"><i class=\"fa-solid fa-user\"></i></a>\r\n");
      out.write("              </li>\r\n");
      out.write("              <!-- SEARCH -->\r\n");
      out.write("              <li><a href=\"#\"><i class=\"fa-solid fa-magnifying-glass\"></i></a></li>\r\n");
      out.write("			  <!-- CART -->\r\n");
      out.write("			  ");

			  	MemberDTO memberdto = (MemberDTO)session.getAttribute("loginInfo");
			  	if(memberdto != null){
			  	int memno = memberdto.getMember_no();
			  	pageContext.setAttribute("memno", memno);
			  	}
			  
      out.write("\r\n");
      out.write("              <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/product_cartList.do?memno=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${memno}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("              <i class=\"fa-solid fa-cart-shopping\"></i></a></li>\r\n");
      out.write("            </ul> \r\n");
      out.write("            ");
} 
      out.write("\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"menu\" id=\"menu\">\r\n");
      out.write("        <div class=\"menu-wrap\">\r\n");
      out.write("          <!-- artist sub menu -->\r\n");
      out.write("          <div id=\"artist-box\">\r\n");
      out.write("            <ul class=\"artist-menu\">\r\n");
      out.write("              <li>\r\n");
      out.write("                <a href=\"#\">SHINEE</a>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li>\r\n");
      out.write("                <a href=\"");
      out.print(request.getContextPath());
      out.write("/artist_content.do?no=22\">싸이</a>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li>\r\n");
      out.write("                <a href=\"#\">(여자)아이들</a>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li>\r\n");
      out.write("                <a href=\"#\">AESPA</a>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li>\r\n");
      out.write("                <a href=\"#\">BTS</a>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li>\r\n");
      out.write("                <a href=\"#\">BLACK PINK</a>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li>\r\n");
      out.write("                <a href=\"#\">RED VELVET</a>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li>\r\n");
      out.write("                <a href=\"#\">박재범</a>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li>\r\n");
      out.write("                <a href=\"#\">STAYC</a>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li>\r\n");
      out.write("                <a href=\"#\">BEAST</a>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li>\r\n");
      out.write("                <a href=\"#\">IVE</a>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li>\r\n");
      out.write("                <a href=\"#\">LE SSERAFIM</a>\r\n");
      out.write("              </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"artist-album\">\r\n");
      out.write("              <div>\r\n");
      out.write("                <div class=\"artist-album-img\">\r\n");
      out.write("                  <img id=\"img\" src=\"\" />\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"artist-album-info\">\r\n");
      out.write("                  <p class=\"artist-album-singer\" id=\"singer\"></p>\r\n");
      out.write("                  <p class=\"artist-album-tit\" id=\"title\"></p>\r\n");
      out.write("                  <a class=\"artist-album-detail-link\" href=\"#\">자세히보기</a>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <!-- product sub menu -->\r\n");
      out.write("          <div id=\"product-box\">\r\n");
      out.write("            <div class=\"product-wrap-vertical\">\r\n");
      out.write("              <div class=\"product-wrap\">\r\n");
      out.write("                <div class=\"tit\"><a href=\"");
      out.print(request.getContextPath());
      out.write("/product_list.do?cno=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${100}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">MUSIC</a></div>\r\n");
      out.write("                <ul class=\"product-menu\">\r\n");
      out.write("                  <li>\r\n");
      out.write("                    <a href=\"");
      out.print(request.getContextPath());
      out.write("/product_list.do?cno=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${110}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">CD</a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li>\r\n");
      out.write("                    <a href=\"");
      out.print(request.getContextPath());
      out.write("/product_list.do?cno=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${120}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">DVD</a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li>\r\n");
      out.write("                    <a href=\"");
      out.print(request.getContextPath());
      out.write("/product_list.do?cno=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${130}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">etc.</a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("              </div>\r\n");
      out.write("\r\n");
      out.write("              <div class=\"product-wrap\">\r\n");
      out.write("                <div class=\"tit\"><a href=\"");
      out.print(request.getContextPath());
      out.write("/product_list.do?cno=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${200}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">PHOTO</a></div>\r\n");
      out.write("                <ul class=\"product-menu\">\r\n");
      out.write("                  <li>\r\n");
      out.write("                    <a href=\"");
      out.print(request.getContextPath());
      out.write("/product_list.do?cno=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${210}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">Printed</a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li>\r\n");
      out.write("                    <a href=\"");
      out.print(request.getContextPath());
      out.write("/product_list.do?cno=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${220}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">Photo Book</a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("              </div>\r\n");
      out.write("\r\n");
      out.write("              <div class=\"product-wrap\">\r\n");
      out.write("                <div class=\"tit\"><a href=\"");
      out.print(request.getContextPath());
      out.write("/product_list.do?cno=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${300}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">CONCERT</a></div>\r\n");
      out.write("                <ul class=\"product-menu\">\r\n");
      out.write("                  <li>\r\n");
      out.write("                    <a href=\"");
      out.print(request.getContextPath());
      out.write("/product_list.do?cno=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${310}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">Official Fanlight</a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li>\r\n");
      out.write("                    <a href=\"");
      out.print(request.getContextPath());
      out.write("/product_list.do?cno=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${320}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">Concert Goods</a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"product-wrap\">\r\n");
      out.write("              <div class=\"tit\"><a href=\"");
      out.print(request.getContextPath());
      out.write("/product_list.do?cno=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${400}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">LIVING</a></div>\r\n");
      out.write("              <ul class=\"product-menu\">\r\n");
      out.write("                \r\n");
      out.write("                <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/product_list.do?cno=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${410}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">Home</a></li>\r\n");
      out.write("                <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/product_list.do?cno=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${420}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">Kitchen</a></li>\r\n");
      out.write("                <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/product_list.do?cno=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${430}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">F&B</a></li>\r\n");
      out.write("                <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/product_list.do?cno=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${440}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">Tech</a></li>\r\n");
      out.write("                <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/product_list.do?cno=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${450}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">Book</a></li>\r\n");
      out.write("                <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/product_list.do?cno=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${460}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">Pet</a></li>\r\n");
      out.write("              </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"product-wrap\">\r\n");
      out.write("              <div class=\"tit\"><a href=\"");
      out.print(request.getContextPath());
      out.write("/product_list.do?cno=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${500}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">BEAUTY</a></div>\r\n");
      out.write("              <ul class=\"product-menu\">\r\n");
      out.write("                \r\n");
      out.write("                <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/product_list.do?cno=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${510}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">Skin Care</a></li>\r\n");
      out.write("                <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/product_list.do?cno=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${520}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">Make Up</a></li>\r\n");
      out.write("                <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/product_list.do?cno=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${530}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">Cleansing</a></li>\r\n");
      out.write("                <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/product_list.do?cno=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${540}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">Body & Hair</a></li>\r\n");
      out.write("                <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/product_list.do?cno=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${550}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">Pack & Masks</a></li>\r\n");
      out.write("                <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/product_list.do?cno=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${560}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">Perfume</a></li>\r\n");
      out.write("	   			<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/product_list.do?cno=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${570}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">Tool</a></li>\r\n");
      out.write("	   			<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/product_list.do?cno=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${580}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">Men's</a></li>\r\n");
      out.write("              </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("          <div class=\"product-wrap\">\r\n");
      out.write("              <div class=\"tit\"><a href=\"");
      out.print(request.getContextPath());
      out.write("/product_list.do?cno=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${600}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">STATIONERY</a></div>\r\n");
      out.write("              <ul class=\"product-menu\">\r\n");
      out.write("                \r\n");
      out.write("                <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/product_list.do?cno=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${610}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">Note</a></li>\r\n");
      out.write("                <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/product_list.do?cno=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${620}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">Office</a></li>\r\n");
      out.write("                <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/product_list.do?cno=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${630}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">Pen</a></li>\r\n");
      out.write("                <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/product_list.do?cno=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${640}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">Deco</a></li>\r\n");
      out.write("                <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/product_list.do?cno=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${650}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">Binder</a></li>\r\n");
      out.write("                <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/product_list.do?cno=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${660}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">Toy</a></li>\r\n");
      out.write("              </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"product-wrap-vertical\">\r\n");
      out.write("        <div class=\"product-wrap\">\r\n");
      out.write("              <div class=\"tit\"><a href=\"");
      out.print(request.getContextPath());
      out.write("/product_list.do?cno=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${700}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">FASHION</a></div>\r\n");
      out.write("              <ul class=\"product-menu\">\r\n");
      out.write("                \r\n");
      out.write("                <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/product_list.do?cno=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${710}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">Clothing</a></li>\r\n");
      out.write("                <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/product_list.do?cno=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${720}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">Acc</a></li>\r\n");
      out.write("                <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/product_list.do?cno=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${730}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">Jewelry</a></li>\r\n");
      out.write("              </ul>\r\n");
      out.write("         </div>\r\n");
      out.write("            \r\n");
      out.write("        <div class=\"product-wrap\">\r\n");
      out.write("              <div class=\"tit\"><a href=\"");
      out.print(request.getContextPath());
      out.write("/product_list.do?cno=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${800}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">CUSTOMIZING</a></div>\r\n");
      out.write("              <ul class=\"product-menu\">\r\n");
      out.write("                \r\n");
      out.write("                <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/product_list.do?cno=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${810}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">Phone Case</a></li>\r\n");
      out.write("                <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/product_list.do?cno=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${820}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">Fashion</a></li>\r\n");
      out.write("                <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/product_list.do?cno=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${830}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">Acc</a></li>\r\n");
      out.write("              </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </header>\r\n");
      out.write("    <!-- include header -->");
      out.write("\r\n");
      out.write("	<div class=\"mypage_container\">\r\n");
      out.write("		\r\n");
      out.write("		<!-- aisde inlcude 추가  -->\r\n");
      out.write("		");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../include/mypage_aside.jsp", out, false);
      out.write("\r\n");
      out.write("		\r\n");
      out.write("		<div class=\"mypage_main\">\r\n");
      out.write("		<div class=\"manage_top\">\r\n");
      out.write("		고객문의 내역\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"qna_notice\">\r\n");
      out.write("			<div class=\"notice_1\">* 현재 답변 대기 중인 문의는 \r\n");
      out.write("				<span>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${waiting }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>건입니다.</div>\r\n");
      out.write("			<div class=\"notice_2\" align=\"right\"><input type=\"button\" value=\"문의하기\" onclick=\"location.href='inquiry_write.do'\"></div>\r\n");
      out.write("		</div>	\r\n");
      out.write("		<form method=\"post\" action=\"");
      out.print(request.getContextPath() );
      out.write("/inquiry_date.do\">\r\n");
      out.write("		<div class=\"qna_month\" align=\"center\">\r\n");
      out.write("			<table>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td>\r\n");
      out.write("						<div class=\"month_area\">\r\n");
      out.write("							<ul>\r\n");
      out.write("								<li class=\"quick_search\" id=\"0\"><label for=\"MONTH0\"><input id=\"MONTH0\" type=\"radio\" name=\"search_date\" value=\"0\" >오늘</label></li>\r\n");
      out.write("								<li class=\"quick_search\" id=\"7\"><label for=\"MONTH0.25\"><input id=\"MONTH0.25\" type=\"radio\" name=\"search_date\" value=\"7\">1주일</label></li>\r\n");
      out.write("								<li class=\"quick_search\" id=\"1\"><label for=\"MONTH1\"><input id=\"MONTH1\" type=\"radio\" name=\"search_date\" value=\"1\">1개월</label></li>\r\n");
      out.write("								<li class=\"quick_search\" id=\"3\"><label for=\"MONTH3\"><input id=\"MONTH3\" type=\"radio\" name=\"search_date\" value=\"3\">3개월</label></li>\r\n");
      out.write("								<li class=\"quick_search\" id=\"6\"><label for=\"MONTH6\"><input id=\"MONTH6\" type=\"radio\" name=\"search_date\" value=\"6\">6개월</label></li>\r\n");
      out.write("								<li class=\"quick_search\" id=\"12\"><label for=\"MONTH12\"><input id=\"MONTH12\" type=\"radio\" name=\"search_date\" value=\"12\">1년</label></li>\r\n");
      out.write("							</ul>\r\n");
      out.write("						</div>\r\n");
      out.write("					</td>\r\n");
      out.write("					<td><input type=\"submit\" value=\"조회\"></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("			</table>\r\n");
      out.write("		</div>\r\n");
      out.write("		</form>\r\n");
      out.write("		<script type=\"text/javascript\">\r\n");
      out.write("			\r\n");
      out.write("			$(document).ready(function(){\r\n");
      out.write("				\r\n");
      out.write("				var preValue=0;\r\n");
      out.write("				var count =0;\r\n");
      out.write("				/* \r\n");
      out.write("				if($(\"input[name='search_date']:checked\")){\r\n");
      out.write("					\r\n");
      out.write("					preValue =$(this).val();\r\n");
      out.write("				} */\r\n");
      out.write("				\r\n");
      out.write("				$(\"input[name='search_date']\").click(function(){\r\n");
      out.write("					\r\n");
      out.write("					if(count >=1){\r\n");
      out.write("						$(\"#\"+check).css('background-color','#ececec');\r\n");
      out.write("						$(\"#\"+preValue).css('background-color', 'white');\r\n");
      out.write("						preValue = String($(this).val());\r\n");
      out.write("					}\r\n");
      out.write("					\r\n");
      out.write("					var check = String($(this).val());\r\n");
      out.write("					preValue = String($(this).val());\r\n");
      out.write("					\r\n");
      out.write("					console.log(\"preValue:\"+preValue);\r\n");
      out.write("					\r\n");
      out.write("					$(\"#\"+check).css('background-color','#e9e3e1');\r\n");
      out.write("					\r\n");
      out.write("					count ++;\r\n");
      out.write("				\r\n");
      out.write("				});\r\n");
      out.write("				\r\n");
      out.write("				\r\n");
      out.write("			});\r\n");
      out.write("		\r\n");
      out.write("		</script>\r\n");
      out.write("		\r\n");
      out.write("		<div class=\"qna_table\">\r\n");
      out.write("		<table>\r\n");
      out.write("			<tr class=\"firstRow\">\r\n");
      out.write("				<th>구분</th>\r\n");
      out.write("				<th>상품정보</th>\r\n");
      out.write("				<th>제목</th>\r\n");
      out.write("				<th>등록일</th>\r\n");
      out.write("				<th>상태</th>\r\n");
      out.write("			</tr>\r\n");
      out.write("			");
      //  c:if
      org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
      boolean _jspx_th_c_005fif_005f0_reused = false;
      try {
        _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
        _jspx_th_c_005fif_005f0.setParent(null);
        // /WEB-INF/views/member/mypage_qnaList.jsp(111,3) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${!empty List }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
        int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
        if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("				");

					List<InquiryDTO> list = (List<InquiryDTO>)request.getAttribute("List");
					List<ProductDTO> pCont = (List<ProductDTO>)request.getAttribute("pCont");
					
					for(int i=0; i<list.size(); i++){
						
						InquiryDTO idto = list.get(i); //문의게시글
						ProductDTO product = pCont.get(i); //제품정보
						
						//카테고리
						String category ="";
						switch(idto.getCategory_inofk()){
						case 1:
							category ="취소/환불";
							break;
						case 2:
							category ="상품문의";
							break;
						case 3:
							category ="배송";
							break;
						case 4:
							category ="교환";
							break;
						case 5:
							category ="기타";
							break;
						}
						
				
            out.write("		\r\n");
            out.write("					<!-- 테이블 행 시작  -->\r\n");
            out.write("					<tr>\r\n");
            out.write("						");
            out.write("			\r\n");
            out.write("						<td class=\"qna_td\">");
            out.print(category );
            out.write("</td>\r\n");
            out.write("					\r\n");
            out.write("					<!-- 상품 정보  -->\r\n");
            out.write("					");
 if(idto.getProduct_no() == 0){ //상품정보가 없으면 
            out.write(" \r\n");
            out.write("						<td class=\"qna_product\"> </td>	\r\n");
            out.write("					");
 }else{ //상품정보가 있으면 
            out.write("\r\n");
            out.write("						<td class=\"qna_product\">\r\n");
            out.write("						<a href=\"");
            out.print(request.getContextPath());
            out.write("/product_detail.do?pno=");
            out.print(product.getProduct_no());
            out.write("\">\r\n");
            out.write("						");
            out.print(product.getProduct_name() );
            out.write("</a>\r\n");
            out.write("						</td>\r\n");
            out.write("					");
}
            out.write("\r\n");
            out.write("						<td class=\"qnaboard_title\">\r\n");
            out.write("							<a href=\"");
            out.print(request.getContextPath());
            out.write("/inquiry_cont.do?no=");
            out.print(idto.getInquiry_no() );
            out.write("&page=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${paging.getPage()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('"');
            out.write('>');
            out.print(idto.getInquiry_title() );
            out.write("</a>\r\n");
            out.write("						</td>\r\n");
            out.write("						<td class=\"qna_td\">");
            out.print(idto.getInquiry_date().substring(0,10) );
            out.write("</td>\r\n");
            out.write("						\r\n");
            out.write("					");
 
						//답변상태
						String status ="";
						
						if(idto.getInquiry_status() == 0){
							status ="답변대기";
					
            out.write("\r\n");
            out.write("						<td class=\"qna_td\">	<span style=\"color:#ff5722;\">");
            out.print(status );
            out.write("</span></td>\r\n");
            out.write("					");
 	}else{
							status ="답변완료";
					
            out.write("\r\n");
            out.write("						<td class=\"qna_td\">	");
            out.print(status );
            out.write("</td>\r\n");
            out.write("					");
 } 
            out.write("	\r\n");
            out.write("						\r\n");
            out.write("						\r\n");
            out.write("					</tr>\r\n");
            out.write("				");
	}
            out.write("\r\n");
            out.write("			");
            int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
        _jspx_th_c_005fif_005f0_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
      }
      out.write("\r\n");
      out.write("		</table>\r\n");
      out.write("		\r\n");
      out.write("		<!-- 페이징 처리 -->\r\n");
      out.write("		<div class=\"table_page\" align=\"center\">\r\n");
      out.write("		");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("		");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		");
      if (_jspx_meth_c_005fif_005f4(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("		\r\n");
      out.write("		</div>\r\n");
      out.write("		\r\n");
      out.write("		</div>	<!-- class=\"qna_table\"  -->\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		</div><!-- class=\"mypage_main\" end -->\r\n");
      out.write("	\r\n");
      out.write("	</div><!-- class=\"mypage_container\" end -->\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <!-- include footer -->\r\n");
      out.write("   <!-- FOOTER -->\r\n");
      out.write("  <footer class=\"footer\">\r\n");
      out.write("	<script src=\"resources/js/gnb.js\"></script>\r\n");
      out.write("	<div class=\"foot_menu\">\r\n");
      out.write("		<ul>\r\n");
      out.write("			<li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/\">Back to top</a></li>\r\n");
      out.write("		</ul>\r\n");
      out.write("	</div>\r\n");
      out.write("    <div id=\"foot_contents\">\r\n");
      out.write("        <h5 id=\"foot_info\"><strong>INFORMATION</strong></h5>\r\n");
      out.write("        <div class=\"company_info\">\r\n");
      out.write("            <ul>\r\n");
      out.write("                <li>상호명 &nbsp;<strong>YOUR CELEB</strong> </li>\r\n");
      out.write("                <li>대표자명 &nbsp;<strong>김돌수</strong></li>\r\n");
      out.write("                <li>주소 &nbsp;<strong>서울특별시 중구 남대문로 120 대일빌딩 2층, 3층</strong></li>\r\n");
      out.write("                \r\n");
      out.write("            </ul>\r\n");
      out.write("            <ul>\r\n");
      out.write("                <li>대표전화 &nbsp;02-1544-9970</li>\r\n");
      out.write("                <li>팩스번호 &nbsp;02-1544-9971 </li>\r\n");
      out.write("                <li>개인정보보호책임자 &nbsp;김돌돌 / idolidol@yourceleb.com </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div id=\"bg_copy\">\r\n");
      out.write("         	<div class=\"wd\">\r\n");
      out.write("	             <div class=\"copy_year\">\r\n");
      out.write("	                 <span class=\"color-red\">YOUR CELEB의 모든 컨텐츠는 저작권의 보호를 받고 있습니다.</span><br>\r\n");
      out.write("						<p>&copy; <span id=\"year\">2022</span> by <strong>YOUR CELEB</strong> All Rights Reserved.</p>\r\n");
      out.write("	             </div>\r\n");
      out.write("	         </div>\r\n");
      out.write("	     </div>\r\n");
      out.write("    </div>\r\n");
      out.write("        \r\n");
      out.write("  </footer>\r\n");
      out.write("    <!-- include footer -->\r\n");
      out.write("	\r\n");
      out.write("	<!-- popup -->\r\n");
      out.write("	\r\n");
      out.write("		\r\n");
      out.write("	");
      if (_jspx_meth_c_005fset_005f3(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("	 <div class=\"swiper popupSwiper\" id=\"popup\">\r\n");
      out.write("	 	<div class=\"swiper-wrapper\">\r\n");
      out.write("			<div class=\"popup-image-area\">\r\n");
      out.write("				");
      if (_jspx_meth_c_005fforEach_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"popup-row\">\r\n");
      out.write("			<label class=\"today-done-label\">\r\n");
      out.write("          		<input type=\"checkbox\" id=\"today-done-checkbox\" />\r\n");
      out.write("          		<span class=\"today-done-text\">오늘은 더 이상 보지않기</span>\r\n");
      out.write("        	</label>\r\n");
      out.write("			<div>\r\n");
      out.write("				<button id=\"popup-close-btn\">닫기</button>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>	\r\n");
      out.write("	</div> \r\n");
      out.write("	 \r\n");
      out.write("</body>\r\n");
      out.write("<script>\r\n");
      out.write("var popup = document.querySelector(\"#popup\");\r\n");
      out.write("var todayIsDone = document.querySelector(\"#today-done-checkbox\");\r\n");
      out.write("var closeBtn = document.querySelector(\"#popup-close-btn\");\r\n");
      out.write("var popupCookieKey = \"today-done\";\r\n");
      out.write("\r\n");
      out.write("const swiper = new Swiper(\".popupSwiper\", {\r\n");
      out.write("    loop: true,\r\n");
      out.write("    autoplay: {\r\n");
      out.write("      delay: 3000,\r\n");
      out.write("    },\r\n");
      out.write("  });\r\n");
      out.write("  \r\n");
      out.write("closeBtn.addEventListener(\"click\", function(){\r\n");
      out.write("	close();\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("function close(){\r\n");
      out.write("	if(todayIsDone.checked){\r\n");
      out.write("		//오늘은 더 이상 보지 않는 로직\r\n");
      out.write("		setCookie(popupCookieKey,todayIsDone.checked,1);\r\n");
      out.write("	}\r\n");
      out.write("	popup.classList.remove(\"show\");\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function setCookie(key, value, days){\r\n");
      out.write("	var expires = \"\";\r\n");
      out.write("    if (days) {\r\n");
      out.write("      var date = new Date();\r\n");
      out.write("      var oneDay = 24 * 60 * 60 * 1000;\r\n");
      out.write("      date.setTime(date.getTime() + days * oneDay);\r\n");
      out.write("      expires = \"; expires=\" + date.toUTCString();\r\n");
      out.write("    }\r\n");
      out.write("    document.cookie = key + \"=\" + (value || \"\") + expires + \"; path=/\";\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  function getCookie(key) {\r\n");
      out.write("    var nameEQ = key + \"=\";\r\n");
      out.write("    var ca = document.cookie.split(\";\");\r\n");
      out.write("    for (var i = 0; i < ca.length; i++) {\r\n");
      out.write("      var c = ca[i];\r\n");
      out.write("      while (c.charAt(0) == \" \") c = c.substring(1, c.length);\r\n");
      out.write("      if (c.indexOf(nameEQ) == 0) return c.substring(nameEQ.length, c.length);\r\n");
      out.write("    }\r\n");
      out.write("    return null;\r\n");
      out.write("  }\r\n");
      out.write("  \r\n");
      out.write("  window.onload = function () {\r\n");
      out.write("      const isAliveCookie = getCookie(popupCookieKey);\r\n");
      out.write("\r\n");
      out.write("      if (!isAliveCookie) {\r\n");
      out.write("        // 쿠키에 어떤 값이 있을때!\r\n");
      out.write("        popup.classList.add(\"show\");\r\n");
      out.write("      }\r\n");
      out.write("    };\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /WEB-INF/views/member/mypage_qnaList.jsp(26,1) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("dto");
      // /WEB-INF/views/member/mypage_qnaList.jsp(26,1) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/member/mypage_qnaList.jsp(26,1) '${loginInfo }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${loginInfo }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f1 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f1_reused = false;
    try {
      _jspx_th_c_005fset_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f1.setParent(null);
      // /WEB-INF/views/member/mypage_qnaList.jsp(27,1) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setVar("list");
      // /WEB-INF/views/member/mypage_qnaList.jsp(27,1) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/member/mypage_qnaList.jsp(27,1) '${List }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${List }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f1 = _jspx_th_c_005fset_005f1.doStartTag();
      if (_jspx_th_c_005fset_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f1);
      _jspx_th_c_005fset_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f2 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f2_reused = false;
    try {
      _jspx_th_c_005fset_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f2.setParent(null);
      // /WEB-INF/views/member/mypage_qnaList.jsp(28,1) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f2.setVar("paging");
      // /WEB-INF/views/member/mypage_qnaList.jsp(28,1) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f2.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/member/mypage_qnaList.jsp(28,1) '${paging }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${paging }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f2 = _jspx_th_c_005fset_005f2.doStartTag();
      if (_jspx_th_c_005fset_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f2);
      _jspx_th_c_005fset_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /WEB-INF/views/member/mypage_qnaList.jsp(183,2) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${paging.getPage() > paging.getBlock() }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write(" <!-- 현재 페이지가 4인데 block사이즈는 3이라면 -->\r\n");
          out.write("			<a href=\"inquiry_list.do?page=1\">[맨 처음]</a>\r\n");
          out.write("			<a href=\"inquiry_list.do?page=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${paging.getStartBlock()-1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">◀</a>\r\n");
          out.write("		");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/views/member/mypage_qnaList.jsp(188,2) name = begin type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setBegin(((java.lang.Integer) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${paging.getStartBlock() }", int.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).intValue());
      // /WEB-INF/views/member/mypage_qnaList.jsp(188,2) name = end type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setEnd(((java.lang.Integer) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${paging.getEndBlock() }", int.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).intValue());
      // /WEB-INF/views/member/mypage_qnaList.jsp(188,2) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("i");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("			\r\n");
            out.write("			");
            if (_jspx_meth_c_005fif_005f2(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("	\r\n");
            out.write("			\r\n");
            out.write("			");
            if (_jspx_meth_c_005fif_005f3(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("\r\n");
            out.write("				\r\n");
            out.write("		");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f2_reused = false;
    try {
      _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /WEB-INF/views/member/mypage_qnaList.jsp(190,3) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${i == paging.getPage() }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
      if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("			<b><a href=\"inquiry_list.do?page=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${i }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write('"');
          out.write('>');
          out.write('[');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${i }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("]</a></b>\r\n");
          out.write("			");
          int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      _jspx_th_c_005fif_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f3 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f3_reused = false;
    try {
      _jspx_th_c_005fif_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /WEB-INF/views/member/mypage_qnaList.jsp(194,3) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f3.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${i != paging.getPage() }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f3 = _jspx_th_c_005fif_005f3.doStartTag();
      if (_jspx_eval_c_005fif_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("			<a href=\"inquiry_list.do?page=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${i }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write('"');
          out.write('>');
          out.write('[');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${i }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("]</a>\r\n");
          out.write("			");
          int evalDoAfterBody = _jspx_th_c_005fif_005f3.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f3);
      _jspx_th_c_005fif_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f4 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f4_reused = false;
    try {
      _jspx_th_c_005fif_005f4.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f4.setParent(null);
      // /WEB-INF/views/member/mypage_qnaList.jsp(201,2) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f4.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${paging.getEndBlock() < paging.getAllPage() }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f4 = _jspx_th_c_005fif_005f4.doStartTag();
      if (_jspx_eval_c_005fif_005f4 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write(" <!-- endBlock이 6인데 allPage가 7이라면 -->\r\n");
          out.write("			<a href=\"inquiry_list.do?page=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${paging.getEndBlock()+1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">▶</a>\r\n");
          out.write("			<a href=\"inquiry_list.do?page=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${paging.getAllPage()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">[마지막으로]</a>\r\n");
          out.write("		");
          int evalDoAfterBody = _jspx_th_c_005fif_005f4.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f4);
      _jspx_th_c_005fif_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f4, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f3 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f3_reused = false;
    try {
      _jspx_th_c_005fset_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f3.setParent(null);
      // /WEB-INF/views/member/../include/user_bottom.jsp(44,1) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f3.setVar("elist");
      // /WEB-INF/views/member/../include/user_bottom.jsp(44,1) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f3.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/member/../include/user_bottom.jsp(44,1) '${elist }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${elist }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f3 = _jspx_th_c_005fset_005f3.doStartTag();
      if (_jspx_th_c_005fset_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f3);
      _jspx_th_c_005fset_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f1_reused = false;
    try {
      _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f1.setParent(null);
      // /WEB-INF/views/member/../include/user_bottom.jsp(48,4) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/member/../include/user_bottom.jsp(48,4) '${elist }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${elist }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/views/member/../include/user_bottom.jsp(48,4) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setVar("edto");
      int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
        if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("					<div class=\"swiper-slide\">\r\n");
            out.write("						<div class=\"swiper-slide-popup-wrap\" >\r\n");
            out.write("							<a href=\"\">\r\n");
            out.write("					 		<img src=\"./resources/upload/images/");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${edto.notice_image }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">\r\n");
            out.write("							<span>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${edto.notice_title }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</span>\r\n");
            out.write("							</a>\r\n");
            out.write("						</div>\r\n");
            out.write("					</div>\r\n");
            out.write("				");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f1);
      _jspx_th_c_005fforEach_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f1_reused);
    }
    return false;
  }
}
