/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.60
 * Generated at: 2022-07-05 06:04:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.include;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class admin_005ftop_005finclude_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1652771076240L));
    _jspx_dependants.put("jar:file:/C:/NCS/workspace(spring)/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/IdolProject/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("		\r\n");
      out.write("	.admin_navbar {\r\n");
      out.write("		display: flex;\r\n");
      out.write("		flex-direction: row;\r\n");
      out.write("		background-color: black;\r\n");
      out.write("		width: 100%;\r\n");
      out.write("		/* 스크롤 다운 시 메뉴바 적용 후 사용\r\n");
      out.write("		position: sticky;\r\n");
      out.write("		top:0px;\r\n");
      out.write("		z-index: 99;\r\n");
      out.write("		*/\r\n");
      out.write("	}	\r\n");
      out.write("	.admin_link {\r\n");
      out.write("		display: flex;\r\n");
      out.write("		flex-direction: row;\r\n");
      out.write("		width: 100%;\r\n");
      out.write("		flex-wrap: wrap;\r\n");
      out.write("		justify-content: space-evenly;\r\n");
      out.write("    	padding-right: 10px;\r\n");
      out.write("		align-items: center;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	.admin_link a {\r\n");
      out.write("		\r\n");
      out.write("		text-decoration: none;\r\n");
      out.write("		font-family: 'Press Start 2P', cursive;\r\n");
      out.write("		color: white;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	.include_top_title {\r\n");
      out.write("		/*font-family: 'Bungee Shade', cursive;*/\r\n");
      out.write("		font-family: 'Press Start 2P', cursive;\r\n");
      out.write("		color: white;\r\n");
      out.write("		width: 130px;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	li {\r\n");
      out.write("		list-style-type: none;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.include_top_title {\r\n");
      out.write("		cursor: pointer;\r\n");
      out.write("		margin-left: 100px;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.admin_id_session {\r\n");
      out.write("		width: 130px;\r\n");
      out.write("		color: white;\r\n");
      out.write("		font-family: 'Creepster', cursive;\r\n");
      out.write("		font-size: 1.3em;\r\n");
      out.write("		padding: 13px 0px 13px 13px;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	.celeb a:hover {\r\n");
      out.write("		color: gold;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	.upBox_icon {\r\n");
      out.write("		\r\n");
      out.write("		font-size: 40px;\r\n");
      out.write("		position: fixed;\r\n");
      out.write("		right: 16px;\r\n");
      out.write("		bottom: 50px;\r\n");
      out.write("		display: none;\r\n");
      out.write("		color: white;\r\n");
      out.write("		cursor: pointer;\r\n");
      out.write("		z-index: 3;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.upBox_icon img:hover {\r\n");
      out.write("		color: red;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.upBox_icon img {\r\n");
      out.write("		width: 50px;\r\n");
      out.write("		height: 50px;\r\n");
      out.write("	}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://kit.fontawesome.com/a705bacd4a.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,0,0\" />\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script src=\"http://code.jquery.com/jquery-3.6.0.js\"></script>\r\n");
      out.write("<script src=\"https://code.jquery.com/ui/1.13.0/jquery-ui.js\" integrity=\"sha256-xH4q8N0pEzrZMaRmd7gQVcTZiFei+HfRTBPJ1OGXC0k=\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("	$(function(){\r\n");
      out.write("		$('.include_top_title').click(function(){\r\n");
      out.write("			location.href='");
      out.print(request.getContextPath());
      out.write("/admin_main.do'\r\n");
      out.write("		});	\r\n");
      out.write("	});\r\n");
      out.write("\r\n");
      out.write("	// welcome 마우스 오버시 로그아웃 애니매이션\r\n");
      out.write("	$(function(){\r\n");
      out.write("		$('.admin_id_session').stop().mouseover(function(){\r\n");
      out.write("			$(this).animate({color:'red' }, 200, function(){\r\n");
      out.write("				$(this).text(\"LOGOUT\");\r\n");
      out.write("			});\r\n");
      out.write("		})\r\n");
      out.write("		.mouseout(function(){\r\n");
      out.write("			$(this).stop().animate({color:'white'}, 200, function(){\r\n");
      out.write("				$(this).text(\"WELLCOME ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${admin_id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" :D\");\r\n");
      out.write("			});\r\n");
      out.write("		})\r\n");
      out.write("		.click(function(){\r\n");
      out.write("			location.href='");
      out.print(request.getContextPath());
      out.write("/admin_logout.do';\r\n");
      out.write("		});\r\n");
      out.write("	});\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	// 마우스 스크롤 애니메이션 탑 버튼 생성\r\n");
      out.write("	$(function(){\r\n");
      out.write("		$(window).scroll(function(){\r\n");
      out.write("			if($(this).scrollTop() >= 300){\r\n");
      out.write("				$('.upBox_icon').fadeIn();\r\n");
      out.write("			}else {\r\n");
      out.write("				$('.upBox_icon').fadeOut();\r\n");
      out.write("			}\r\n");
      out.write("		});\r\n");
      out.write("		\r\n");
      out.write("		$('.upBox_icon').click(function(){\r\n");
      out.write("			\r\n");
      out.write("			$('html, body').stop().animate({scrollTop:0},500);\r\n");
      out.write("		});\r\n");
      out.write("	});\r\n");
      out.write("	\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("		<!-- include  -->\r\n");
      out.write("		<div class=\"admin_navbar\">\r\n");
      out.write("		\r\n");
      out.write("			<div class=\"include_top_title\">\r\n");
      out.write("				<h2>YOUR CELEB</h2>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"admin_link\">\r\n");
      out.write("				<div class=\"celeb\">\r\n");
      out.write("					<a href=\"");
      out.print(request.getContextPath() );
      out.write("/admin_celeb_list.do\">\r\n");
      out.write("						CELEB\r\n");
      out.write("					</a>\r\n");
      out.write("				</div>\r\n");
      out.write("				<!--<div>\r\n");
      out.write("					<a href=\"");
      out.print(request.getContextPath() );
      out.write("/admin_celeb_insert.do\">\r\n");
      out.write("						INSERT\r\n");
      out.write("					</a>\r\n");
      out.write("				</div>-->\r\n");
      out.write("				<div>\r\n");
      out.write("					<a href=\"");
      out.print(request.getContextPath() );
      out.write("/admin_group_list.do\">\r\n");
      out.write("						GROUP\r\n");
      out.write("					</a>\r\n");
      out.write("				</div>\r\n");
      out.write("				<!-- <div>\r\n");
      out.write("					<a href=\"");
      out.print(request.getContextPath() );
      out.write("/admin_group_insert.do\">\r\n");
      out.write("						INSERT\r\n");
      out.write("					</a> \r\n");
      out.write("				</div>	-->\r\n");
      out.write("				<div>\r\n");
      out.write("					<a href=\"");
      out.print(request.getContextPath() );
      out.write("/admin_music_list.do\">\r\n");
      out.write("						MUSIC\r\n");
      out.write("					</a>\r\n");
      out.write("				</div>\r\n");
      out.write("				<!--<div>\r\n");
      out.write("					<a href=\"");
      out.print(request.getContextPath() );
      out.write("/admin_music_insert.do\">\r\n");
      out.write("						INSERT\r\n");
      out.write("					</a>\r\n");
      out.write("				</div>	-->			\r\n");
      out.write("				<div>\r\n");
      out.write("					<a href=\"");
      out.print(request.getContextPath() );
      out.write("/admin_images_list.do\">\r\n");
      out.write("						IMAGES\r\n");
      out.write("					</a>\r\n");
      out.write("				</div>\r\n");
      out.write("				<!--<div>\r\n");
      out.write("					<a href=\"");
      out.print(request.getContextPath() );
      out.write("/admin_image_insert.do\">\r\n");
      out.write("						INSERT \r\n");
      out.write("					</a>\r\n");
      out.write("				</div>-->	\r\n");
      out.write("				<div>\r\n");
      out.write("					<a href=\"");
      out.print(request.getContextPath() );
      out.write("/admin_notice_list.do\">\r\n");
      out.write("						NOTICE\r\n");
      out.write("					</a>\r\n");
      out.write("				</div>\r\n");
      out.write("				\r\n");
      out.write("				<div>\r\n");
      out.write("					<a href=\"");
      out.print(request.getContextPath() );
      out.write("/admin_products_list.do\">\r\n");
      out.write("						PRODUCTS\r\n");
      out.write("					</a>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div>\r\n");
      out.write("					<a href=\"");
      out.print(request.getContextPath() );
      out.write("/admin_member_main.do\">\r\n");
      out.write("						MEMBER						\r\n");
      out.write("					</a>\r\n");
      out.write("				</div>\r\n");
      out.write("				<!--<div>\r\n");
      out.write("					<a>INSERT</a>\r\n");
      out.write("				</div>-->	\r\n");
      out.write("				\r\n");
      out.write("				<div class=\"admin_id_session\" style=\"cursor: pointer\">\r\n");
      out.write("					WELLCOME ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${admin_id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" :D\r\n");
      out.write("				</div>\r\n");
      out.write("			\r\n");
      out.write("			</div> <!-- admin_link -->\r\n");
      out.write("			\r\n");
      out.write("		</div> <!-- admin_navbar end -->\r\n");
      out.write("			\r\n");
      out.write("	\r\n");
      out.write("	<div class=\"upBox_icon\">\r\n");
      out.write("	 <!--  <i class=\"fa-solid fa-arrow-up-long\"></i> -->\r\n");
      out.write("	<img alt=\"\" src=\"./resources/icon/ghost.gif\">\r\n");
      out.write("</div>\r\n");
      out.write("	\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
