/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.60
 * Generated at: 2022-07-05 05:48:26 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.ranking;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.idol.model.MemberDTO;

public final class detail_005franking_005flist_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(6);
    _jspx_dependants.put("/WEB-INF/views/ranking/../include/ranking_sidebar.jsp", Long.valueOf(1656644152989L));
    _jspx_dependants.put("jar:file:/C:/NCS/workspace(spring)/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/IdolProject/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/views/ranking/../include/user_top.jsp", Long.valueOf(1656999173032L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1652771076240L));
    _jspx_dependants.put("jar:file:/C:/NCS/workspace(spring)/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/IdolProject/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/views/ranking/../include/user_bottom.jsp", Long.valueOf(1656999173028L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.idol.model.MemberDTO");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write(".rankWrapper{\r\n");
      out.write("	width: 980px;\r\n");
      out.write("	min-height: 80%;\r\n");
      out.write("	margin: 0 auto;\r\n");
      out.write("	margin-top: 40px;\r\n");
      out.write("	display: flex;\r\n");
      out.write("}\r\n");
      out.write(".sidenav {\r\n");
      out.write("  height: 100%;\r\n");
      out.write("  width: 240px;\r\n");
      out.write("  z-index: 1;\r\n");
      out.write("  top: 100px;\r\n");
      out.write("  left: 250px;\r\n");
      out.write("  background-color: white;\r\n");
      out.write("  overflow-x: hidden;\r\n");
      out.write("  padding-top: 20px;\r\n");
      out.write("  \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".sidenav_menu{\r\n");
      out.write("padding-bottom: 16px;\r\n");
      out.write("}\r\n");
      out.write(".sidenav a {\r\n");
      out.write("  padding: 6px 6px 6px 6px;\r\n");
      out.write("  text-decoration: none;\r\n");
      out.write("  font-size: 20px;\r\n");
      out.write("  color: #242424;\r\n");
      out.write("  display: block;\r\n");
      out.write("  padding-bottom:\r\n");
      out.write("}\r\n");
      out.write(".sidenav a:hover {\r\n");
      out.write("  color: red;\r\n");
      out.write("}\r\n");
      out.write(".main {\r\n");
      out.write("  margin-left: 200px; /* Same as the width of the sidenav */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".rank_header{\r\n");
      out.write("border-top: 1px solid lightgray;\r\n");
      out.write("height: 100%;\r\n");
      out.write("width: 720px;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".rank_header ul li{\r\n");
      out.write("border-bottom: 1px solid lightgray;\r\n");
      out.write("padding-top: 16px;\r\n");
      out.write("display:flex;\r\n");
      out.write("justify-content:center;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("@media screen and (max-height: 450px) {\r\n");
      out.write("  .sidenav {padding-top: 15px;}\r\n");
      out.write("  .sidenav a {font-size: 16px;}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".rankContent_row_image{\r\n");
      out.write("width:48px;\r\n");
      out.write("height:48px;\r\n");
      out.write("padding-bottom: 16px;\r\n");
      out.write("margin-right: 8px;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".rankContent_row_image img{\r\n");
      out.write("width:48px;\r\n");
      out.write("height:48px;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".rankContent_wrap{\r\n");
      out.write("width:550px;\r\n");
      out.write("height:80px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("	<head>\r\n");
      out.write("		<meta charset=\"UTF-8\">\r\n");
      out.write("		<link rel=\"stylesheet\" href=\"./resources/css/all.min.css\">\r\n");
      out.write("		<link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("		<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("		<link href=\"https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@300;400;500;700&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("	    <link rel=\"stylesheet\" href=\"./resources/css/global.css\" />\r\n");
      out.write("	    <link rel=\"stylesheet\" href=\"./resources/css/gnb.css\" />\r\n");
      out.write("	    <link rel=\"stylesheet\" href=\"./resources/css/main.css\" />\r\n");
      out.write("	    <link\r\n");
      out.write("	      rel=\"stylesheet\"\r\n");
      out.write("	      href=\"https://unpkg.com/swiper@8/swiper-bundle.min.css\"\r\n");
      out.write("	    />\r\n");
      out.write("    	<script src=\"https://unpkg.com/swiper@8/swiper-bundle.min.js\"></script>\r\n");
      out.write("		<title>YOUR CELEB</title>\r\n");
      out.write("		<script type=\"text/javascript\">\r\n");
      out.write("		function loginAlert() {\r\n");
      out.write("		      alert(\"사용 권한이 없습니다. 로그인 해주세요\");\r\n");
      out.write("		  } \r\n");
      out.write("		</script>\r\n");
      out.write("	</head>\r\n");
      out.write("	<body>\r\n");
      out.write("		<!-- include header -->\r\n");
      out.write("              <div id=\"g_nav\">\r\n");
      out.write("                 <ul class=\"main_login_section\">\r\n");
      out.write("				");
 if(session.getAttribute("login_id") == null){ 
				 
      out.write("\r\n");
      out.write("           			<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/login.do\">Login</a></li>\r\n");
      out.write("          			<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/join.do\">Join</a></li>\r\n");
      out.write("				");
} else{ 
      out.write("\r\n");
      out.write("                    <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/logout.do\">Logout</a></li>\r\n");
      out.write("                ");
} 
      out.write("	\r\n");
      out.write("                 </ul>\r\n");
      out.write("              </div>\r\n");
      out.write("   		<header id=\"header\">\r\n");
      out.write("      <div class=\"gnb\">\r\n");
      out.write("        <div class=\"gnb-wrap\">\r\n");
      out.write("	      <div class=\"logo\"><a href=\"");
      out.print(request.getContextPath());
      out.write("/\"><img src=\"././resources/upload/logo.png\"></a></div>\r\n");
      out.write("          <div class=\"gnb-menu\">\r\n");
      out.write("            <ul>\r\n");
      out.write("              <li>\r\n");
      out.write("                <a href=\"#\" class=\"active-link\" id=\"artist\">ARTIST</a>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li>\r\n");
      out.write("                <a href=\"");
      out.print(request.getContextPath());
      out.write("/product_list.do?cno=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${100}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" class=\"active-link\" id=\"product\">PRODUCT</a>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/community_boardList.do\">FORUM</a></li>\r\n");
      out.write("              <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/event_list.do?board_id=1&category_id=1\">EVENT</a></li>\r\n");
      out.write("              <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/whole_ranking.do\">MEMBERS</a></li>\r\n");
      out.write("              <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/used_list.do\">MARKET</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("            \r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("          <div class=\"gnb-tool\">\r\n");
      out.write("            <ul>\r\n");
      out.write("            <!-- 로그인이 안 되어 있을 경우 -->\r\n");
      out.write("            ");
 if(session.getAttribute("login_id")==null){ 
      out.write("\r\n");
      out.write("              <li>\r\n");
      out.write("              <!-- MYPAGE -->\r\n");
      out.write("                <a href=\"#\" onclick=\"loginAlert()\"><i class=\"fa-solid fa-user\"></i></a>\r\n");
      out.write("              </li>\r\n");
      out.write("              <!-- SEARCH -->\r\n");
      out.write("              <li><a href=\"#\"><i class=\"fa-solid fa-magnifying-glass\"></i></a></li>\r\n");
      out.write("				\r\n");
      out.write("			  <!-- CART -->\r\n");
      out.write("              <li><a href=\"#\" onclick=\"loginAlert()\"><i class=\"fa-solid fa-cart-shopping\"></i></a></li>\r\n");
      out.write("            \r\n");
      out.write("            </ul>\r\n");
      out.write("            ");
}else { 
      out.write("\r\n");
      out.write("            <ul>\r\n");
      out.write("              <li>\r\n");
      out.write("              <!-- MYPAGE -->\r\n");
      out.write("                <a href=\"");
      out.print(request.getContextPath());
      out.write("/myfeed.do?id=");
      out.print((String)session.getAttribute("login_id"));
      out.write("\"><i class=\"fa-solid fa-user\"></i></a>\r\n");
      out.write("              </li>\r\n");
      out.write("              <!-- SEARCH -->\r\n");
      out.write("              <li><a href=\"#\"><i class=\"fa-solid fa-magnifying-glass\"></i></a></li>\r\n");
      out.write("			  <!-- CART -->\r\n");
      out.write("			  ");

			  	MemberDTO memberdto = (MemberDTO)session.getAttribute("loginInfo");
			  	if(memberdto != null){
			  	int memno = memberdto.getMember_no();
			  	pageContext.setAttribute("memno", memno);
			  	}
			  
      out.write("\r\n");
      out.write("              <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/product_cartList.do?memno=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${memno}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("              <i class=\"fa-solid fa-cart-shopping\"></i></a></li>\r\n");
      out.write("            </ul> \r\n");
      out.write("            ");
} 
      out.write("\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"menu\" id=\"menu\">\r\n");
      out.write("        <div class=\"menu-wrap\">\r\n");
      out.write("          <!-- artist sub menu -->\r\n");
      out.write("          <div id=\"artist-box\">\r\n");
      out.write("            <ul class=\"artist-menu\">\r\n");
      out.write("              <li>\r\n");
      out.write("                <a href=\"");
      out.print(request.getContextPath());
      out.write("/group_content.do?group=SHINEE\">SHINEE</a>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li>\r\n");
      out.write("                <a href=\"");
      out.print(request.getContextPath());
      out.write("/artist_content.do?no=22\">싸이</a>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li>\r\n");
      out.write("                <a href=\"#\">(여자)아이들</a>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li>\r\n");
      out.write("                <a href=\"");
      out.print(request.getContextPath());
      out.write("/group_content.do?group=AESPA\">AESPA</a>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li>\r\n");
      out.write("                <a href=\"");
      out.print(request.getContextPath());
      out.write("/group_content.do?group=방탄소년단(BTS)\">BTS</a>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li>\r\n");
      out.write("                <a href=\"");
      out.print(request.getContextPath());
      out.write("/group_content.do?group=BLACKPINK\">BLACK PINK</a>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li>\r\n");
      out.write("                <a href=\"");
      out.print(request.getContextPath());
      out.write("/group_content.do?group=레드벨벳\">RED VELVET</a>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li>\r\n");
      out.write("                <a href=\"");
      out.print(request.getContextPath());
      out.write("/artist_content.do?no=32\">박재범</a>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li>\r\n");
      out.write("                <a href=\"");
      out.print(request.getContextPath());
      out.write("/group_content.do?group=STAYC\">STAYC</a>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li>\r\n");
      out.write("                <a href=\"#\">BEAST</a>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li>\r\n");
      out.write("                <a href=\"");
      out.print(request.getContextPath());
      out.write("/group_content.do?group=IVE\">IVE</a>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li>\r\n");
      out.write("                <a href=\"");
      out.print(request.getContextPath());
      out.write("/group_content.do?group=LE SSERAFIM\">LE SSERAFIM</a>\r\n");
      out.write("              </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"artist-album\">\r\n");
      out.write("              <div>\r\n");
      out.write("                <div class=\"artist-album-img\">\r\n");
      out.write("                  <img id=\"img\" src=\"\" />\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"artist-album-info\">\r\n");
      out.write("                  <p class=\"artist-album-singer\" id=\"singer\"></p>\r\n");
      out.write("                  <p class=\"artist-album-tit\" id=\"title\"></p>\r\n");
      out.write("                  <a class=\"artist-album-detail-link\" href=\"#\">자세히보기</a>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <!-- product sub menu -->\r\n");
      out.write("          <div id=\"product-box\">\r\n");
      out.write("            <div class=\"product-wrap-vertical\">\r\n");
      out.write("              <div class=\"product-wrap\">\r\n");
      out.write("                <div class=\"tit\"><a href=\"");
      out.print(request.getContextPath());
      out.write("/product_list.do?cno=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${100}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">MUSIC</a></div>\r\n");
      out.write("                <ul class=\"product-menu\">\r\n");
      out.write("                  <li>\r\n");
      out.write("                    <a href=\"");
      out.print(request.getContextPath());
      out.write("/product_list.do?cno=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${110}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">CD</a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li>\r\n");
      out.write("                    <a href=\"");
      out.print(request.getContextPath());
      out.write("/product_list.do?cno=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${120}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">DVD</a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li>\r\n");
      out.write("                    <a href=\"");
      out.print(request.getContextPath());
      out.write("/product_list.do?cno=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${130}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">etc.</a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("              </div>\r\n");
      out.write("\r\n");
      out.write("              <div class=\"product-wrap\">\r\n");
      out.write("                <div class=\"tit\"><a href=\"");
      out.print(request.getContextPath());
      out.write("/product_list.do?cno=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${200}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">PHOTO</a></div>\r\n");
      out.write("                <ul class=\"product-menu\">\r\n");
      out.write("                  <li>\r\n");
      out.write("                    <a href=\"");
      out.print(request.getContextPath());
      out.write("/product_list.do?cno=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${210}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">Printed</a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li>\r\n");
      out.write("                    <a href=\"");
      out.print(request.getContextPath());
      out.write("/product_list.do?cno=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${220}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">Photo Book</a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("              </div>\r\n");
      out.write("\r\n");
      out.write("              <div class=\"product-wrap\">\r\n");
      out.write("                <div class=\"tit\"><a href=\"");
      out.print(request.getContextPath());
      out.write("/product_list.do?cno=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${300}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">CONCERT</a></div>\r\n");
      out.write("                <ul class=\"product-menu\">\r\n");
      out.write("                  <li>\r\n");
      out.write("                    <a href=\"");
      out.print(request.getContextPath());
      out.write("/product_list.do?cno=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${310}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">Official Fanlight</a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li>\r\n");
      out.write("                    <a href=\"");
      out.print(request.getContextPath());
      out.write("/product_list.do?cno=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${320}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">Concert Goods</a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"product-wrap\">\r\n");
      out.write("              <div class=\"tit\"><a href=\"");
      out.print(request.getContextPath());
      out.write("/product_list.do?cno=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${400}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">LIVING</a></div>\r\n");
      out.write("              <ul class=\"product-menu\">\r\n");
      out.write("                \r\n");
      out.write("                <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/product_list.do?cno=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${410}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">Home</a></li>\r\n");
      out.write("                <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/product_list.do?cno=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${420}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">Kitchen</a></li>\r\n");
      out.write("                <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/product_list.do?cno=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${430}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">F&B</a></li>\r\n");
      out.write("                <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/product_list.do?cno=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${440}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">Tech</a></li>\r\n");
      out.write("                <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/product_list.do?cno=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${450}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">Book</a></li>\r\n");
      out.write("                <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/product_list.do?cno=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${460}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">Pet</a></li>\r\n");
      out.write("              </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"product-wrap\">\r\n");
      out.write("              <div class=\"tit\"><a href=\"");
      out.print(request.getContextPath());
      out.write("/product_list.do?cno=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${500}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">BEAUTY</a></div>\r\n");
      out.write("              <ul class=\"product-menu\">\r\n");
      out.write("                \r\n");
      out.write("                <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/product_list.do?cno=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${510}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">Skin Care</a></li>\r\n");
      out.write("                <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/product_list.do?cno=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${520}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">Make Up</a></li>\r\n");
      out.write("                <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/product_list.do?cno=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${530}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">Cleansing</a></li>\r\n");
      out.write("                <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/product_list.do?cno=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${540}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">Body & Hair</a></li>\r\n");
      out.write("                <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/product_list.do?cno=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${550}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">Pack & Masks</a></li>\r\n");
      out.write("                <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/product_list.do?cno=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${560}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">Perfume</a></li>\r\n");
      out.write("	   			<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/product_list.do?cno=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${570}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">Tool</a></li>\r\n");
      out.write("	   			<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/product_list.do?cno=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${580}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">Men's</a></li>\r\n");
      out.write("              </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("          <div class=\"product-wrap\">\r\n");
      out.write("              <div class=\"tit\"><a href=\"");
      out.print(request.getContextPath());
      out.write("/product_list.do?cno=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${600}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">STATIONERY</a></div>\r\n");
      out.write("              <ul class=\"product-menu\">\r\n");
      out.write("                \r\n");
      out.write("                <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/product_list.do?cno=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${610}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">Note</a></li>\r\n");
      out.write("                <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/product_list.do?cno=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${620}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">Office</a></li>\r\n");
      out.write("                <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/product_list.do?cno=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${630}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">Pen</a></li>\r\n");
      out.write("                <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/product_list.do?cno=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${640}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">Deco</a></li>\r\n");
      out.write("                <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/product_list.do?cno=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${650}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">Binder</a></li>\r\n");
      out.write("                <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/product_list.do?cno=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${660}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">Toy</a></li>\r\n");
      out.write("              </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"product-wrap-vertical\">\r\n");
      out.write("        <div class=\"product-wrap\">\r\n");
      out.write("              <div class=\"tit\"><a href=\"");
      out.print(request.getContextPath());
      out.write("/product_list.do?cno=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${700}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">FASHION</a></div>\r\n");
      out.write("              <ul class=\"product-menu\">\r\n");
      out.write("                \r\n");
      out.write("                <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/product_list.do?cno=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${710}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">Clothing</a></li>\r\n");
      out.write("                <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/product_list.do?cno=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${720}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">Acc</a></li>\r\n");
      out.write("                <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/product_list.do?cno=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${730}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">Jewelry</a></li>\r\n");
      out.write("              </ul>\r\n");
      out.write("         </div>\r\n");
      out.write("            \r\n");
      out.write("        <div class=\"product-wrap\">\r\n");
      out.write("              <div class=\"tit\"><a href=\"");
      out.print(request.getContextPath());
      out.write("/product_list.do?cno=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${800}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">CUSTOMIZING</a></div>\r\n");
      out.write("              <ul class=\"product-menu\">\r\n");
      out.write("                \r\n");
      out.write("                <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/product_list.do?cno=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${810}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">Phone Case</a></li>\r\n");
      out.write("                <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/product_list.do?cno=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${820}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">Fashion</a></li>\r\n");
      out.write("                <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/product_list.do?cno=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${830}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">Acc</a></li>\r\n");
      out.write("              </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </header>\r\n");
      out.write("    <!-- include header -->");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	<div class=\"rankWrapper\">\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write(".rankWrapper{\r\n");
      out.write("	width: 980px;\r\n");
      out.write("	min-height: 80%;\r\n");
      out.write("	margin: 0 auto;\r\n");
      out.write("	margin-top: 40px;\r\n");
      out.write("	display: flex;\r\n");
      out.write("}\r\n");
      out.write(".sidenav {\r\n");
      out.write("  height: 100%;\r\n");
      out.write("  width: 240px;\r\n");
      out.write("  z-index: 1;\r\n");
      out.write("  top: 100px;\r\n");
      out.write("  left: 250px;\r\n");
      out.write("  background-color: white;\r\n");
      out.write("  overflow-x: hidden;\r\n");
      out.write("  padding-top: 20px;\r\n");
      out.write("  \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".sidenav_menu{\r\n");
      out.write("padding-bottom: 16px;\r\n");
      out.write("}\r\n");
      out.write(".sidenav a {\r\n");
      out.write("  padding: 6px 6px 6px 6px;\r\n");
      out.write("  text-decoration: none;\r\n");
      out.write("  font-size: 20px;\r\n");
      out.write("  color: #242424;\r\n");
      out.write("  display: block;\r\n");
      out.write("  padding-bottom:\r\n");
      out.write("}\r\n");
      out.write(".sidenav a:hover {\r\n");
      out.write("  color: red;\r\n");
      out.write("}\r\n");
      out.write(".main {\r\n");
      out.write("  margin-left: 200px; /* Same as the width of the sidenav */\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	\r\n");
      out.write("	<div class=\"sidenav\">\r\n");
      out.write("			<div class=\"sidenav_menu\">\r\n");
      out.write("				<a href=\"");
      out.print(request.getContextPath());
      out.write("/whole_ranking.do\">Overview</a>\r\n");
      out.write("				<a href=\"");
      out.print(request.getContextPath());
      out.write("/detail_ranking.do?key=point\">Most points</a>\r\n");
      out.write("  				<a href=\"");
      out.print(request.getContextPath());
      out.write("/detail_ranking.do?key=purchase\">Most purchase</a>\r\n");
      out.write("  				<a href=\"");
      out.print(request.getContextPath());
      out.write("/detail_ranking.do?key=message\">Most message</a>\r\n");
      out.write("  				<a href=\"");
      out.print(request.getContextPath());
      out.write("/detail_ranking.do?key=comment\">Most comment</a>\r\n");
      out.write("  				<!-- 게시글 추천수 많은 순.. community_recommend -->\r\n");
      out.write("				<a href=\"");
      out.print(request.getContextPath());
      out.write("/detail_ranking.do?key=referrals\">Most referrals</a>\r\n");
      out.write("  				<a href=\"");
      out.print(request.getContextPath());
      out.write("/detail_ranking.do?key=birth\">Today's birthdays</a>\r\n");
      out.write("  				<a href=\"");
      out.print(request.getContextPath());
      out.write("/chat.do\">chatting</a>\r\n");
      out.write("  			</div>\r\n");
      out.write("  			<form method=\"get\" action='");
      out.print(request.getContextPath());
      out.write("/detail_ranking.do'>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"sidenav_container\">\r\n");
      out.write("					<h3 class=\"container_header\">\r\n");
      out.write("						Find member\r\n");
      out.write("					</h3>\r\n");
      out.write("					<div class=\"members_search_board\">\r\n");
      out.write("						<input type=\"hidden\" value='");
      out.print(request.getParameter("key") );
      out.write("' name=\"key\">\r\n");
      out.write("						<input type=\"text\" class=\"input\"name=\"keyword\" placeholder=\"Nickname..\">&nbsp;&nbsp;\r\n");
      out.write("						<input type=\"submit\" value=\"검색\">\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</form>\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("		\r\n");
      out.write("		");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("		");
      if (_jspx_meth_c_005fset_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("		<div class=\"rank_wrapper\">\r\n");
      out.write("			<h2>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${title }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h2>\r\n");
      out.write("			<div class=\"rank_header\">\r\n");
      out.write("			");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("			");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("	<script src=\"resources/js/gnb.js\"></script>\r\n");
      out.write("	<script\r\n");
      out.write("	  src=\"https://code.jquery.com/jquery-3.6.0.min.js\"\r\n");
      out.write("	  integrity=\"sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=\"\r\n");
      out.write("	  crossorigin=\"anonymous\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<!-- include footer -->\r\n");
      out.write(" 	<!-- FOOTER -->\r\n");
      out.write("	 <footer class=\"footer\">\r\n");
      out.write("	\r\n");
      out.write("	<div class=\"foot_menu\">\r\n");
      out.write("		<ul>\r\n");
      out.write("			<li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/\">Back to top</a></li>\r\n");
      out.write("		</ul>\r\n");
      out.write("	</div>\r\n");
      out.write("	   <div id=\"foot_contents\">\r\n");
      out.write("	       <h5 id=\"foot_info\"><strong>INFORMATION</strong></h5>\r\n");
      out.write("	       <div class=\"company_info\">\r\n");
      out.write("	           <ul>\r\n");
      out.write("	               <li>상호명 &nbsp;<strong>YOUR CELEB</strong> </li>\r\n");
      out.write("	               <li>대표자명 &nbsp;<strong>김돌수</strong></li>\r\n");
      out.write("	               <li>주소 &nbsp;<strong>서울특별시 중구 남대문로 120 대일빌딩 2층, 3층</strong></li>\r\n");
      out.write("	               \r\n");
      out.write("	           </ul>\r\n");
      out.write("	           <ul>\r\n");
      out.write("	               <li>대표전화 &nbsp;02-1544-9970</li>\r\n");
      out.write("	               <li>팩스번호 &nbsp;02-1544-9971 </li>\r\n");
      out.write("	               <li>개인정보보호책임자 &nbsp;김돌돌 / idolidol@yourceleb.com </li>\r\n");
      out.write("	           </ul>\r\n");
      out.write("	       </div>\r\n");
      out.write("	       <div id=\"bg_copy\">\r\n");
      out.write("	        	<div class=\"wd\">\r\n");
      out.write("	             <div class=\"copy_year\">\r\n");
      out.write("	                 <span class=\"color-red\">YOUR CELEB의 모든 컨텐츠는 저작권의 보호를 받고 있습니다.</span><br>\r\n");
      out.write("						<p>&copy; <span id=\"year\">2022</span> by <strong>YOUR CELEB</strong> All Rights Reserved.</p>\r\n");
      out.write("	             </div>\r\n");
      out.write("	         </div>\r\n");
      out.write("	     </div>\r\n");
      out.write("	   </div>\r\n");
      out.write("	</footer>\r\n");
      out.write("	<!-- include footer -->\r\n");
      out.write("	\r\n");
      out.write("	<!-- popup -->\r\n");
      out.write("	 <div id=\"popup\">\r\n");
      out.write("	 	<div class=\"swiper popupSwiper\">\r\n");
      out.write("	 		<div class=\"swiper-wrapper\">\r\n");
      out.write("				<!-- ajax를 이용해서 swiper-slide를 append 해준다. -->\r\n");
      out.write("			</div>	\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"popup-row\">\r\n");
      out.write("			<label class=\"today-done-label\">\r\n");
      out.write("          		<input type=\"checkbox\" id=\"today-done-checkbox\" />\r\n");
      out.write("          		<span class=\"today-done-text\">오늘은 더 이상 보지않기</span>\r\n");
      out.write("        	</label>\r\n");
      out.write("			<div>\r\n");
      out.write("				<button id=\"popup-close-btn\">닫기</button>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>	\r\n");
      out.write("	</div> \r\n");
      out.write("	\r\n");
      out.write("	</body>\r\n");
      out.write("	<script>\r\n");
      out.write("		var popup = document.querySelector(\"#popup\");\r\n");
      out.write("		var todayIsDone = document.querySelector(\"#today-done-checkbox\");\r\n");
      out.write("		var closeBtn = document.querySelector(\"#popup-close-btn\");\r\n");
      out.write("		var popupCookieKey = \"today-done\";\r\n");
      out.write("		\r\n");
      out.write("		$.ajax({\r\n");
      out.write("			url: \"/IdolProject/event_popup_items.do\",\r\n");
      out.write("			method: \"GET\",\r\n");
      out.write("			dataType: \"json\",\r\n");
      out.write("			success (response) {\r\n");
      out.write("				// response 는 배열이다. [{image, bid, no}, ...]\r\n");
      out.write("				var swiperWrapper = document.querySelector(\".popupSwiper .swiper-wrapper\")\r\n");
      out.write("				\r\n");
      out.write("				for (var i = 0; i < response.length; i++) {\r\n");
      out.write("					var item = response[i];\r\n");
      out.write("					\r\n");
      out.write("					var swiperSlide = document.createElement(\"div\");\r\n");
      out.write("					swiperSlide.className = \"swiper-slide\";\r\n");
      out.write("					\r\n");
      out.write("					var swiperSlidePopupWrap = document.createElement(\"div\");\r\n");
      out.write("					swiperSlidePopupWrap.className = \"swiper-slide-popup-wrap\";\r\n");
      out.write("					\r\n");
      out.write("					var anchor = document.createElement(\"a\");\r\n");
      out.write("					anchor.href = \"");
      out.print(request.getContextPath());
      out.write("/event_cont.do?category_id=1&board_id=\"+ item.bid +\"&no=\" + item.no\r\n");
      out.write("				\r\n");
      out.write("					var img = document.createElement(\"img\");\r\n");
      out.write("					img.src = \"./resources/upload/notice/\" + item.image\r\n");
      out.write("					\r\n");
      out.write("					anchor.appendChild(img)\r\n");
      out.write("					swiperSlidePopupWrap.appendChild(anchor)\r\n");
      out.write("					swiperSlide.appendChild(swiperSlidePopupWrap)\r\n");
      out.write("					swiperWrapper.appendChild(swiperSlide)\r\n");
      out.write("				}\r\n");
      out.write("				\r\n");
      out.write("				const popupSwiper = new Swiper(\".popupSwiper\", {\r\n");
      out.write("				    loop: true,\r\n");
      out.write("				    autoplay: {\r\n");
      out.write("				      delay: 3000,\r\n");
      out.write("				    },\r\n");
      out.write("				  });\r\n");
      out.write("				\r\n");
      out.write("			},\r\n");
      out.write("			error(err) {\r\n");
      out.write("				console.log(err)\r\n");
      out.write("			}\r\n");
      out.write("		})\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("\r\n");
      out.write("		closeBtn.addEventListener(\"click\", function(){\r\n");
      out.write("			close();\r\n");
      out.write("		});\r\n");
      out.write("		\r\n");
      out.write("		function close(){\r\n");
      out.write("			if(todayIsDone.checked){\r\n");
      out.write("				//오늘은 더 이상 보지 않는 로직\r\n");
      out.write("				setCookie(popupCookieKey,todayIsDone.checked,1);\r\n");
      out.write("			}\r\n");
      out.write("			popup.classList.remove(\"show\");\r\n");
      out.write("			sessionStorage.setItem(\"popup-close\", \"close\")\r\n");
      out.write("		}\r\n");
      out.write("	\r\n");
      out.write("		function setCookie(key, value, days){\r\n");
      out.write("			var expires = \"\";\r\n");
      out.write("		    if (days) {\r\n");
      out.write("		      var date = new Date();\r\n");
      out.write("		      var oneDay = 24 * 60 * 60 * 1000;\r\n");
      out.write("		      date.setTime(date.getTime() + days * oneDay);\r\n");
      out.write("		      expires = \"; expires=\" + date.toUTCString();\r\n");
      out.write("		    }\r\n");
      out.write("		    document.cookie = key + \"=\" + (value || \"\") + expires + \"; path=/\";\r\n");
      out.write("		  }\r\n");
      out.write("	\r\n");
      out.write("		function getCookie(key) {\r\n");
      out.write("		  var nameEQ = key + \"=\";\r\n");
      out.write("		  var ca = document.cookie.split(\";\");\r\n");
      out.write("		  for (var i = 0; i < ca.length; i++) {\r\n");
      out.write("		    var c = ca[i];\r\n");
      out.write("		    while (c.charAt(0) == \" \") c = c.substring(1, c.length);\r\n");
      out.write("		    if (c.indexOf(nameEQ) == 0) return c.substring(nameEQ.length, c.length);\r\n");
      out.write("		  }\r\n");
      out.write("		  return null;\r\n");
      out.write("		}\r\n");
      out.write("	  \r\n");
      out.write("		window.onload = function () {\r\n");
      out.write("		    const isAliveCookie = getCookie(popupCookieKey);\r\n");
      out.write("		    var isClosed = sessionStorage.getItem(\"popup-close\")\r\n");
      out.write("		\r\n");
      out.write("		    if (!isAliveCookie && !isClosed) {\r\n");
      out.write("		      // 쿠키에 어떤 값이 없을때!\r\n");
      out.write("		      popup.classList.add(\"show\");\r\n");
      out.write("		    }\r\n");
      out.write("		 };\r\n");
      out.write("	</script>\r\n");
      out.write("</html>\r\n");
      out.write("  ");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /WEB-INF/views/ranking/detail_ranking_list.jsp(97,2) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("title");
      // /WEB-INF/views/ranking/detail_ranking_list.jsp(97,2) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/ranking/detail_ranking_list.jsp(97,2) '${title }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${title }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f1 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f1_reused = false;
    try {
      _jspx_th_c_005fset_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f1.setParent(null);
      // /WEB-INF/views/ranking/detail_ranking_list.jsp(98,2) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setVar("list");
      // /WEB-INF/views/ranking/detail_ranking_list.jsp(98,2) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/ranking/detail_ranking_list.jsp(98,2) '${rankList }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${rankList }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f1 = _jspx_th_c_005fset_005f1.doStartTag();
      if (_jspx_th_c_005fset_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f1);
      _jspx_th_c_005fset_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/ranking/detail_ranking_list.jsp(102,3) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.size() <= 0 }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("				<div>\r\n");
          out.write("					<ul class=\"no_user\">\r\n");
          out.write("						<li>No users match the specified criteria</li>\r\n");
          out.write("					</ul>\r\n");
          out.write("				</div>\r\n");
          out.write("			");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /WEB-INF/views/ranking/detail_ranking_list.jsp(109,3) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.size() > 0}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("				");
          if (_jspx_meth_c_005fforEach_005f0(_jspx_th_c_005fif_005f1, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("			");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f1);
      // /WEB-INF/views/ranking/detail_ranking_list.jsp(110,4) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/ranking/detail_ranking_list.jsp(110,4) '${list }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${list }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/views/ranking/detail_ranking_list.jsp(110,4) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("dto");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("					<ul>\r\n");
            out.write("						<li>\r\n");
            out.write("							<div class=\"rankContent_row_image\">\r\n");
            out.write("								<img src=\"./resources/upload/member_image/");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.member_no }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('/');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.member_image }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">\r\n");
            out.write("							</div>\r\n");
            out.write("							<div class=\"rankContent_wrap\">\r\n");
            out.write("								<div class=\"rankContent_row_header\">\r\n");
            out.write("									<span >");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.member_nickname }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</span>\r\n");
            out.write("								</div>\r\n");
            out.write("								<div class=\"rankContent_row_introduce\">\r\n");
            out.write("									<a>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.member_introduction }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</a>\r\n");
            out.write("								</div>\r\n");
            out.write("							</div>\r\n");
            out.write("							\r\n");
            out.write("							");
            if (_jspx_meth_c_005fif_005f2(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("\r\n");
            out.write("							");
            if (_jspx_meth_c_005fif_005f3(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("\r\n");
            out.write("						</li>\r\n");
            out.write("					</ul>\r\n");
            out.write("				");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f2_reused = false;
    try {
      _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /WEB-INF/views/ranking/detail_ranking_list.jsp(125,7) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.score <= 0 }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
      if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("								<div>\r\n");
          out.write("									\r\n");
          out.write("								</div>\r\n");
          out.write("							");
          int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      _jspx_th_c_005fif_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f3 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f3_reused = false;
    try {
      _jspx_th_c_005fif_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /WEB-INF/views/ranking/detail_ranking_list.jsp(130,7) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f3.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.score > 0 }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f3 = _jspx_th_c_005fif_005f3.doStartTag();
      if (_jspx_eval_c_005fif_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("							<div class=\"rankContent_row_score\">\r\n");
          out.write("								");
          if (_jspx_meth_fmt_005fformatNumber_005f0(_jspx_th_c_005fif_005f3, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
            return true;
          out.write("\r\n");
          out.write("							</div>\r\n");
          out.write("							");
          int evalDoAfterBody = _jspx_th_c_005fif_005f3.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f3);
      _jspx_th_c_005fif_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fformatNumber_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f3, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:formatNumber
    org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag _jspx_th_fmt_005fformatNumber_005f0 = (org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag) _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag.class);
    boolean _jspx_th_fmt_005fformatNumber_005f0_reused = false;
    try {
      _jspx_th_fmt_005fformatNumber_005f0.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fformatNumber_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f3);
      // /WEB-INF/views/ranking/detail_ranking_list.jsp(132,8) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatNumber_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.score }", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_fmt_005fformatNumber_005f0 = _jspx_th_fmt_005fformatNumber_005f0.doStartTag();
      if (_jspx_th_fmt_005fformatNumber_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fnobody.reuse(_jspx_th_fmt_005fformatNumber_005f0);
      _jspx_th_fmt_005fformatNumber_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fformatNumber_005f0, _jsp_getInstanceManager(), _jspx_th_fmt_005fformatNumber_005f0_reused);
    }
    return false;
  }
}
